# Generated by Django 5.1.1 on 2025-03-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_category_name_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='Category',
        ),
    ]
